### ISSUE TITLE
Community Add-Ons

### ISSUE THREAD

**Issue by dubilla** [philippbosch/haz#3]
It would be great to add all/some of the tests from Community Add-Ons.  In particular, I'd love to see the overflow-scrolling test added.

Would a fork that adds a build of Modernizr with those tests added be all that's needed?

**Comment by philippbosch** [comment]
Most of the Community Add-Ons (including overflow-scrolling) have been added to haz.io back in November. 

![overflow-scrolling support](http://f.cl.ly/items/0U3e2C2E0B2q3p1E291g/Screen%20Shot%202012-01-13%20at%209.33.14%20PM.png)
